# $FreeBSD$

PORTNAME=	libevent
PORTVERSION=	6.6.20191030
CATEGORIES=	devel

MAINTAINER=	koue@chaosophia.net
COMMENT=	OpenBSD libevent

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes
GH_ACCOUNT=	koue
GH_PROJECT=	libevent

MAKE_ARGS+=	BINDIR=${PREFIX}/sbin MANDIR=${PREFIX}/man/man

.include <bsd.port.mk>
